openapi: 3.0.3
info:
  title: OpenAPI schema for template terraform-kubernetes-containerservice
components:
  schemas:
    variables:
      required:
      - containers
      type: object
      properties:
        context:
          title: Context
          type: object
          description: |
            Receive contextual information. When Walrus deploys, Walrus will inject specific contextual information into this field.

            Examples:
            ```
            context:
              project:
                name: string
                id: string
              environment:
                name: string
                id: string
              resource:
                name: string
                id: string
            ```
          default: {}
          additionalProperties:
            type: object
          x-walrus-ui:
            group: Basic
            hidden: true
        infrastructure:
          title: Infrastructure
          type: object
          description: |
            Specify the infrastructure information for deploying.

            Examples:
            ```
            infrastructure:
              namespace: string, optional
              gpu_vendor: string, optional
              domain_suffix: string, optional
            ```
          default: {}
          properties:
            domain_suffix:
              title: Domain Suffix
              type: string
            gpu_vendor:
              title: Gpu Vendor
              type: string
            namespace:
              title: Namespace
              type: string
          x-walrus-ui:
            group: Basic
        deployment:
          title: Deployment
          type: object
          description: "Specify the deployment action, like scaling, scheduling, security
            and so on.\n\nExamples:\n```\ndeployment:\n  timeout: number, optional\n
            \ replicas: number, optional\n  rolling: \n    max_surge: number, optional
            \         # in fraction, i.e. 0.25, 0.5, 1\n    max_unavailable: number,
            optional    # in fraction, i.e. 0.25, 0.5, 1\n  fs_group: number, optional\n
            \ sysctls:\n  - name: string\n    value: string\n```\n"
          properties:
            fs_group:
              title: Fs Group
              type: number
            replicas:
              default: 1
              title: Replicas
              type: number
            rolling:
              properties:
                max_surge:
                  default: 0.25
                  title: Max Surge
                  type: number
                max_unavailable:
                  default: 0.25
                  title: Max Unavailable
                  type: number
              title: Rolling
              type: object
            sysctls:
              items:
                properties:
                  name:
                    title: Name
                    type: string
                  value:
                    title: Value
                    type: string
                required:
                - name
                - value
                type: object
              title: Sysctls
              type: array
            timeout:
              default: 0
              title: Timeout
              type: number
          x-walrus-ui:
            group: Basic
        containers:
          title: Containers
          type: array
          description: |
            Specify the container items to deploy.

            Examples:
            ```
            containers:
            - profile: init/run
              image: string
              execute:
                working_dir: string, optional
                command: list(string), optional
                args: list(string), optional
                readonly_rootfs: bool, optional
                as_user: number, optional
                as_group: number, optional
              resources:
                cpu: number, optional               # in oneCPU, i.e. 0.25, 0.5, 1, 2, 4
                memory: number, optional            # in megabyte
                gpu: number, optional               # in oneGPU, i.e. 1, 2, 4
              envs:
              - name: string
                value: string, optional             # accpet changed and restart
                value_refer:                        # donot accpet changed
                  schema: string
                  params: map(any)
              files:
              - path: string
                mode: string, optional
                content: string, optional           # accpet changed but not restart
                content_refer:                      # donot accpet changed
                  schema: string
                  params: map(any)
              mounts:
              - path: string
                readonly: bool, optional
                subpath: string, optional
                volume: string, optional            # shared between containers if named, otherwise exclusively by this container
                volume_refer:
                  schema: string
                  params: map(any)
              ports:
              - internal: number
                external: number, optional
                protocol: tcp/udp/sctp
              checks:
              - type: execute/tcp/grpc/http/https
                delay: number, optional
                interval: number, optional
                timeout: number, optional
                retries: number, optional
                teardown: bool, optional
                execute:
                  command: list(string)
                tcp:
                  port: number
                grpc:
                  port: number
                  service: string, optional
                http:
                  port: number
                  headers: map(string), optional
                  path: string, optional
                https:
                  port: number
                  headers: map(string), optional
                  path: string, optional
            ```
          items:
            properties:
              checks:
                items:
                  properties:
                    delay:
                      title: Delay
                      type: number
                    execute:
                      properties:
                        command:
                          items:
                            type: string
                          title: Command
                          type: array
                      required:
                      - command
                      title: Execute
                      type: object
                    grpc:
                      properties:
                        port:
                          title: Port
                          type: number
                        service:
                          title: Service
                          type: string
                      required:
                      - port
                      title: Grpc
                      type: object
                    http:
                      properties:
                        headers:
                          additionalProperties:
                            type: string
                          title: Headers
                          type: object
                        path:
                          title: Path
                          type: string
                        port:
                          title: Port
                          type: number
                      required:
                      - port
                      title: Http
                      type: object
                    https:
                      properties:
                        headers:
                          additionalProperties:
                            type: string
                          title: Headers
                          type: object
                        path:
                          title: Path
                          type: string
                        port:
                          title: Port
                          type: number
                      required:
                      - port
                      title: Https
                      type: object
                    interval:
                      title: Interval
                      type: number
                    retries:
                      title: Retries
                      type: number
                    tcp:
                      properties:
                        port:
                          title: Port
                          type: number
                      required:
                      - port
                      title: Tcp
                      type: object
                    teardown:
                      title: Teardown
                      type: boolean
                    timeout:
                      title: Timeout
                      type: number
                    type:
                      title: Type
                      type: string
                  required:
                  - type
                  type: object
                title: Checks
                type: array
              envs:
                items:
                  properties:
                    name:
                      title: Name
                      type: string
                    value:
                      title: Value
                      type: string
                    value_refer:
                      properties:
                        params:
                          additionalProperties:
                            type: object
                          title: Params
                          type: object
                        schema:
                          title: Schema
                          type: string
                      required:
                      - params
                      - schema
                      title: Value Refer
                      type: object
                  required:
                  - name
                  type: object
                title: Envs
                type: array
              execute:
                properties:
                  args:
                    items:
                      type: string
                    title: Args
                    type: array
                  as_group:
                    title: As Group
                    type: number
                  as_user:
                    title: As User
                    type: number
                  command:
                    items:
                      type: string
                    title: Command
                    type: array
                  readonly_rootfs:
                    title: Readonly Rootfs
                    type: boolean
                  working_dir:
                    title: Working Dir
                    type: string
                title: Execute
                type: object
              files:
                items:
                  properties:
                    content:
                      title: Content
                      type: string
                    content_refer:
                      properties:
                        params:
                          additionalProperties:
                            type: object
                          title: Params
                          type: object
                        schema:
                          title: Schema
                          type: string
                      required:
                      - params
                      - schema
                      title: Content Refer
                      type: object
                    mode:
                      title: Mode
                      type: string
                    path:
                      title: Path
                      type: string
                  required:
                  - path
                  type: object
                title: Files
                type: array
              image:
                title: Image
                type: string
              mounts:
                items:
                  properties:
                    path:
                      title: Path
                      type: string
                    readonly:
                      title: Readonly
                      type: boolean
                    subpath:
                      title: Subpath
                      type: string
                    volume:
                      title: Volume
                      type: string
                    volume_refer:
                      properties:
                        params:
                          additionalProperties:
                            type: object
                          title: Params
                          type: object
                        schema:
                          title: Schema
                          type: string
                      required:
                      - params
                      - schema
                      title: Volume Refer
                      type: object
                  required:
                  - path
                  type: object
                title: Mounts
                type: array
              ports:
                items:
                  properties:
                    external:
                      title: External
                      type: number
                    internal:
                      title: Internal
                      type: number
                    protocol:
                      title: Protocol
                      type: string
                  required:
                  - internal
                  type: object
                title: Ports
                type: array
              profile:
                title: Profile
                type: string
              resources:
                properties:
                  cpu:
                    title: Cpu
                    type: number
                  gpu:
                    title: Gpu
                    type: number
                  memory:
                    title: Memory
                    type: number
                title: Resources
                type: object
            required:
            - image
            type: object
          x-walrus-ui:
            group: Basic
